require('dotenv').config();
const mongoose = require('mongoose');
const Vendor = require('./models/Vendor');

const vendors = [
  {
    name: 'Lumière Photography',
    category: 'Photography',
    shortDescription: 'Award-winning wedding photography capturing timeless moments with artistic vision.',
    description: 'Lumière Photography is a premier wedding photography studio with over a decade of experience. Our team of passionate photographers use a blend of documentary and fine-art techniques to create images that tell your unique love story. From intimate elopements to grand celebrations, we approach every wedding with creativity, discretion, and genuine emotion.',
    location: 'Connaught Place, New Delhi',
    city: 'New Delhi',
    priceRange: { min: 80000, max: 250000, currency: 'INR' },
    coverImage: 'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800',
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=800',
      'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800',
    ],
    contactEmail: 'hello@lumiere.in',
    contactPhone: '+91 98765 43210',
    tags: ['candid', 'fine-art', 'destination', 'pre-wedding'],
    featured: true,
    verified: true,
    servicesOffered: ['Wedding Photography', 'Pre-Wedding Shoot', 'Engagement Photography', 'Album Design'],
    yearsOfExperience: 11,
    eventsCompleted: 420,
    reviews: [
      { userName: 'Priya Sharma', rating: 5, comment: 'Absolutely stunning photos! They captured our day perfectly.' },
      { userName: 'Arjun Mehta', rating: 5, comment: 'Professional, creative, and so easy to work with.' },
    ],
    averageRating: 5,
    totalReviews: 2,
  },
  {
    name: 'The Palace Grounds',
    category: 'Venue',
    shortDescription: 'A regal heritage venue set across 8 acres of manicured gardens in the heart of Jaipur.',
    description: "The Palace Grounds is one of Jaipur's most iconic wedding destinations. Built in the tradition of Rajput architecture, our estate offers a breathtaking backdrop for weddings of all sizes. With multiple event spaces — from intimate garden ceremonies to grand ballroom receptions — we offer comprehensive hospitality, in-house catering, and dedicated event coordination.",
    location: 'Civil Lines, Jaipur',
    city: 'Jaipur',
    priceRange: { min: 500000, max: 2500000, currency: 'INR' },
    coverImage: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    ],
    contactEmail: 'events@palacegrounds.in',
    contactPhone: '+91 98234 56789',
    tags: ['heritage', 'outdoor', 'grand', 'destination'],
    featured: true,
    verified: true,
    servicesOffered: ['Wedding Venue', 'Outdoor Ceremonies', 'Banquet Hall', 'Accommodation', 'In-house Catering'],
    yearsOfExperience: 18,
    eventsCompleted: 850,
    reviews: [
      { userName: 'Kavya Nair', rating: 5, comment: 'The most beautiful venue we have ever seen. Our guests were in awe.' },
      { userName: 'Rohit Gupta', rating: 4, comment: 'Stunning venue, excellent service. Worth every rupee.' },
    ],
    averageRating: 4.5,
    totalReviews: 2,
  },
  {
    name: 'Saffron & Rose Catering',
    category: 'Catering',
    shortDescription: 'Artisanal wedding catering blending traditional Indian flavours with contemporary presentation.',
    description: 'Saffron & Rose Catering has been redefining wedding food experiences for over 15 years. Our culinary team specialises in live stations, multi-cuisine spreads, and custom menus crafted around your cultural traditions and personal tastes. From Rajasthani thali spreads to Continental buffets and intimate sit-down dinners, every dish is prepared with the finest ingredients and presented with elegance.',
    location: 'Koramangala, Bengaluru',
    city: 'Bengaluru',
    priceRange: { min: 1200, max: 4500, currency: 'INR' },
    coverImage: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    ],
    contactEmail: 'bookings@saffronrose.in',
    contactPhone: '+91 80987 65432',
    tags: ['multi-cuisine', 'live-stations', 'veg', 'non-veg'],
    featured: true,
    verified: true,
    servicesOffered: ['Wedding Catering', 'Live Food Stations', 'Custom Menu Design', 'Dessert Stations', 'Bar Setup'],
    yearsOfExperience: 15,
    eventsCompleted: 1200,
    reviews: [
      { userName: 'Meena Krishnan', rating: 5, comment: 'The food was the talk of the wedding! Absolutely delicious.' },
    ],
    averageRating: 5,
    totalReviews: 1,
  },
  {
    name: 'Cinemoire Films',
    category: 'Videography',
    shortDescription: 'Cinematic wedding films that feel like love stories you will watch for decades.',
    description: 'Cinemoire creates wedding films with a distinctive editorial, cinematic sensibility. We combine drone cinematography, handheld documentary moments, and cinematic colour grading to produce films that genuinely move people. Our films have screened at film festivals and have been featured in major wedding publications. We work across India and internationally.',
    location: 'Bandra, Mumbai',
    city: 'Mumbai',
    priceRange: { min: 120000, max: 400000, currency: 'INR' },
    coverImage: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800',
    ],
    contactEmail: 'hello@cinemoire.in',
    contactPhone: '+91 99876 54321',
    tags: ['cinematic', 'drone', 'destination', 'editorial'],
    featured: false,
    verified: true,
    servicesOffered: ['Wedding Film', 'Same-Day Edit', 'Pre-Wedding Film', 'Drone Cinematography', 'Highlight Reel'],
    yearsOfExperience: 8,
    eventsCompleted: 250,
    reviews: [],
    averageRating: 0,
    totalReviews: 0,
  },
  {
    name: 'Blossoms by Ananya',
    category: 'Florist',
    shortDescription: 'Luxury floral design studio creating lush, romantic installations for discerning couples.',
    description: 'Blossoms by Ananya is a boutique floral design studio based in Chennai. Founded by renowned floral artist Ananya Iyer, the studio creates extraordinary floral installations — from dramatic altar arches and mandap décor to table centrepieces and floral walls. We source seasonal and exotic blooms and work closely with each couple to craft a floral narrative unique to their love story.',
    location: 'Nungambakkam, Chennai',
    city: 'Chennai',
    priceRange: { min: 60000, max: 500000, currency: 'INR' },
    coverImage: 'https://images.unsplash.com/photo-1487530811015-780dab18b5a2?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1465495976277-a703f4e6ca13?w=800',
      'https://images.unsplash.com/photo-1520763185298-1b434c919102?w=800',
    ],
    contactEmail: 'ananya@blossomsbyananya.in',
    contactPhone: '+91 90876 54321',
    tags: ['luxury', 'installations', 'mandap', 'exotic-blooms'],
    featured: false,
    verified: true,
    servicesOffered: ['Mandap Decoration', 'Floral Arches', 'Table Centrepieces', 'Bridal Bouquet', 'Floral Wall'],
    yearsOfExperience: 9,
    eventsCompleted: 310,
    reviews: [
      { userName: 'Divya Rajan', rating: 5, comment: 'The mandap was an absolute dream. Beyond our expectations!' },
    ],
    averageRating: 5,
    totalReviews: 1,
  },
  {
    name: 'Sonata Events',
    category: 'Music & DJ',
    shortDescription: 'Premium live music and DJ entertainment for weddings that guests remember forever.',
    description: "Sonata Events provides world-class wedding entertainment across India. Our roster includes award-winning DJs, live bands, ghazal artists, and fusion ensembles. We customise every performance playlist and set around the couple's music tastes and wedding culture. Full sound and lighting equipment included, with crew.",
    location: 'Jubilee Hills, Hyderabad',
    city: 'Hyderabad',
    priceRange: { min: 50000, max: 350000, currency: 'INR' },
    coverImage: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800',
    gallery: [],
    contactEmail: 'bookings@sonataevents.in',
    contactPhone: '+91 93456 78901',
    tags: ['live-band', 'dj', 'ghazal', 'fusion'],
    featured: false,
    verified: true,
    servicesOffered: ['Wedding DJ', 'Live Band', 'Sound System', 'Lighting Setup', 'Sangeet Entertainment'],
    yearsOfExperience: 12,
    eventsCompleted: 600,
    reviews: [],
    averageRating: 0,
    totalReviews: 0,
  },
  {
    name: 'Aura Bridal Studio',
    category: 'Bridal Wear',
    shortDescription: 'Bespoke bridal couture and lehenga design for the modern Indian bride.',
    description: 'Aura Bridal Studio is a premium bridal couture house offering custom-designed lehengas, sarees, and Indo-western ensembles. Our master artisans blend traditional hand-embroidery techniques — zardozi, gota patti, and resham — with contemporary silhouettes. Every creation is a one-of-a-kind masterpiece tailored exclusively for you.',
    location: 'Lajpat Nagar, New Delhi',
    city: 'New Delhi',
    priceRange: { min: 75000, max: 600000, currency: 'INR' },
    coverImage: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800',
    gallery: [],
    contactEmail: 'studio@aurabridal.in',
    contactPhone: '+91 97654 32109',
    tags: ['couture', 'lehenga', 'bespoke', 'zardozi'],
    featured: false,
    verified: true,
    servicesOffered: ['Bridal Lehenga', 'Wedding Saree', 'Groom Sherwani', 'Indo-Western', 'Alteration'],
    yearsOfExperience: 7,
    eventsCompleted: 180,
    reviews: [],
    averageRating: 0,
    totalReviews: 0,
  },
  {
    name: 'Vows & Vision Planning Co.',
    category: 'Wedding Planner',
    shortDescription: 'Full-service luxury wedding planning with meticulous attention to detail.',
    description: 'Vows & Vision is a full-service wedding planning company offering end-to-end event management for luxury weddings across India and internationally. Our seasoned planners handle vendor coordination, timeline management, budget planning, decor curation, and day-of logistics — so you can be fully present for every beautiful moment.',
    location: 'Worli, Mumbai',
    city: 'Mumbai',
    priceRange: { min: 200000, max: 1500000, currency: 'INR' },
    coverImage: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800',
    gallery: [],
    contactEmail: 'plan@vowsandvision.in',
    contactPhone: '+91 98234 10987',
    tags: ['full-service', 'luxury', 'destination', 'coordination'],
    featured: true,
    verified: true,
    servicesOffered: ['Full Wedding Planning', 'Day-of Coordination', 'Budget Management', 'Vendor Sourcing', 'Destination Weddings'],
    yearsOfExperience: 10,
    eventsCompleted: 380,
    reviews: [
      { userName: 'Shruti Kapoor', rating: 5, comment: 'They made our wedding completely stress-free. Incredible team!' },
      { userName: 'Vikram Singh', rating: 5, comment: 'Every detail was perfect. Could not have done it without them.' },
    ],
    averageRating: 5,
    totalReviews: 2,
  },
  {
    name: 'Glow Bridal Beauty',
    category: 'Makeup & Beauty',
    shortDescription: 'Celebrity makeup artists and bridal beauty specialists for your most radiant day.',
    description: "Glow Bridal Beauty is Bengaluru's most sought-after bridal beauty team. Our certified makeup artists and hair stylists have worked with Bollywood celebrities and are fluent in traditional South Indian, North Indian, and Western bridal aesthetics. We offer airbrush makeup, HD photography makeup, and full-day beauty packages.",
    location: 'Indiranagar, Bengaluru',
    city: 'Bengaluru',
    priceRange: { min: 25000, max: 150000, currency: 'INR' },
    coverImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800',
    gallery: [],
    contactEmail: 'bookings@glowbridal.in',
    contactPhone: '+91 80765 43219',
    tags: ['airbrush', 'celebrity-artists', 'HD-makeup', 'bridal'],
    featured: false,
    verified: false,
    servicesOffered: ['Bridal Makeup', 'Airbrush Makeup', 'Hair Styling', 'Pre-Bridal', 'Group Packages'],
    yearsOfExperience: 6,
    eventsCompleted: 290,
    reviews: [],
    averageRating: 0,
    totalReviews: 0,
  },
  {
    name: 'Royal Decor House',
    category: 'Decor',
    shortDescription: 'Transformative wedding décor creating dreamlike environments from entrance to stage.',
    description: 'Royal Decor House specialises in complete wedding décor and event design. From thematic mandap setups and stage backdrops to table décor, entrance frames, and lighting installations, we transform any venue into an enchanted world. Our in-house inventory includes thousands of props, drapes, and custom fabrication capabilities.',
    location: 'Salt Lake, Kolkata',
    city: 'Kolkata',
    priceRange: { min: 150000, max: 1200000, currency: 'INR' },
    coverImage: 'https://images.unsplash.com/photo-1478147427282-58a87a433128?w=800',
    gallery: [],
    contactEmail: 'design@royaldecorhouse.in',
    contactPhone: '+91 99432 10876',
    tags: ['thematic', 'mandap', 'stage-decor', 'fairy-lights'],
    featured: false,
    verified: true,
    servicesOffered: ['Mandap Setup', 'Stage Decoration', 'Table Centrepieces', 'Entrance Décor', 'Lighting Design'],
    yearsOfExperience: 13,
    eventsCompleted: 540,
    reviews: [],
    averageRating: 0,
    totalReviews: 0,
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/eternal-vows');
    console.log('Connected to MongoDB');

    await Vendor.deleteMany({});
    await Vendor.insertMany(vendors);
    console.log(`✅ Seeded ${vendors.length} vendors`);

    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
}

seed();
